accent = "#B96A30"
cursor = "#B59B73"
foreground = "#1E1A16"
background = "#E8DCC2"
selection_foreground = "#1E1A16"
selection_background = "#D3BF9A"

color0  = "#D3BF9A"
color1  = "#B4543A"
color2  = "#99722E"
color3  = "#B96A30"
color4  = "#3F6473"
color5  = "#B96A30"
color6  = "#5A7F90"
color7  = "#1E1A16"
color8  = "#B59B73"
color9  = "#B4543A"
color10 = "#99722E"
color11 = "#B96A30"
color12 = "#3F6473"
color13 = "#B96A30"
color14 = "#5A7F90"
color15 = "#553d25"